### ISSUE TITLE
Installation using sdist fails

### ISSUE THREAD

**Issue by aaltat** [robotframework/rellu#9]
When installing rellu 0.4 with pip I get error: 
```
~/workspace/SeleniumLibrary$ sudo pip install -r requirements-build.txt 
The directory '/home/godtdd/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/godtdd/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: invoke>=0.20 in /usr/local/lib/python2.7/dist-packages (from -r requirements-build.txt (line 2))
Collecting rellu>=0.4 (from -r requirements-build.txt (line 3))
  Downloading rellu-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k5Sqv7/rellu/setup.py", line 23, in <module>
        with open(join(CURDIR, 'requirements.txt')) as requirements:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-k5Sqv7/rellu/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k5Sqv7/rellu/
~/workspace/SeleniumLibrary$ 
```

**Comment by pekkaklarck** [comment]
1. I guess this is due to `setup.py` reading requirements from `requirements.txt` and that file not being included into the source distribution. I guess we need to create `MANIFEST.in` and include it there.

2. I cannot reproduce this myself. My guess is that I always get the wheel distribution and installing it doesn't use `setup.py` at all.

3. You seem to use Python 2.7 for installation which isn't supported anyway.

4. Need to check this also with SeleniumLibrary. It is likely to have the same problem after my recent `MANIFEST.in` cleanup.

**Comment by pekkaklarck** [comment]
There's actually an easy way to reproduce this:

    pip install dist/rellu-0.4.tar.gz

**Comment by pekkaklarck** [comment]
Adding MANIFEST.in fixed the problem. Can you @aaltat test does installing 0.4 work with Python 3.6? If not, I can create rellu 0.5 ASAP and move remaining issues in it into v0.6.

**Comment by aaltat** [comment]
It works with Python 3.6
